-- ==========================================
-- Migration: vendors master + bookings.vendor_id + akumulasi fee/bukti bulanan
-- Jalankan di Supabase SQL Editor (idempotent)
-- ==========================================

CREATE TABLE IF NOT EXISTS vendors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(32) UNIQUE,
  name TEXT NOT NULL,
  display_name TEXT,
  whatsapp VARCHAR(32),
  email TEXT,
  address TEXT,
  notes TEXT,
  fee_per_booking INTEGER NOT NULL DEFAULT 200000,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE vendors ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY vendors_public_read ON vendors FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY vendors_public_insert ON vendors FOR INSERT WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE POLICY admin_all_vendors ON vendors
    FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- index aktif
CREATE INDEX IF NOT EXISTS idx_vendors_is_active ON vendors(is_active);
CREATE INDEX IF NOT EXISTS idx_vendors_name ON vendors USING gin (to_tsvector('simple', name));

-- bookings -> vendor_id (nullable, menjaga data lama yang hanya pakai vendor_name/source)
DO $$ BEGIN
  ALTER TABLE bookings ADD COLUMN vendor_id BIGINT REFERENCES vendors(id) ON DELETE SET NULL;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS idx_bookings_vendor_id ON bookings(vendor_id);
CREATE INDEX IF NOT EXISTS idx_bookings_vendor_name ON bookings(vendor_name);

-- seed: migrasi nama vendor lama dari bookings biar tidak ada duplikat null
DO $$
DECLARE
  r RECORD;
  vid BIGINT;
BEGIN
  FOR r IN
    SELECT DISTINCT trim(b.vendor_name) AS n, min(b.id) as sample
    FROM bookings b
    WHERE b.source = 'VENDOR' AND b.vendor_name IS NOT NULL AND trim(b.vendor_name) <> ''
      AND b.vendor_id IS NULL
    GROUP BY 1
  LOOP
    SELECT id INTO vid FROM vendors WHERE lower(name) = lower(r.n) LIMIT 1;
    IF vid IS NULL THEN
      INSERT INTO vendors(name, display_name, fee_per_booking)
      VALUES (r.n, r.n, 200000)
      RETURNING id INTO vid;
    END IF;
    UPDATE bookings SET vendor_id = vid
    WHERE trim(coalesce(vendor_name,'') ) = r.n AND vendor_id IS NULL AND source='VENDOR';
  END LOOP;
END $$;

-- auto code jika null: VEND-0001
CREATE OR REPLACE FUNCTION vendors_set_code() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.code IS NULL OR NEW.code = '' THEN
    NEW.code := 'VEND-' || lpad(NEW.id::text, 4, '0');
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_vendors_code ON vendors;
CREATE TRIGGER trg_vendors_code BEFORE INSERT ON vendors
  FOR EACH ROW EXECUTE FUNCTION vendors_set_code();

-- Backfill code untuk row lama NULL
UPDATE vendors SET code = 'VEND-' || lpad(id::text, 4, '0') WHERE code IS NULL OR code = '';
