-- Testimoni + status workflow baru.
-- Jalankan di Supabase SQL Editor.

DO $$ BEGIN
  ALTER TYPE workflow_status_type ADD VALUE IF NOT EXISTS 'EDIT_DONE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE workflow_status_type ADD VALUE IF NOT EXISTS 'PRINT_DONE';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE workflow_status_type ADD VALUE IF NOT EXISTS 'RECEIVED';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

UPDATE project_progress
SET progress_status = 'PRINT_DONE'
WHERE progress_status::text = 'READY';

CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE UNIQUE,
  client_name VARCHAR NOT NULL,
  rating INT NOT NULL DEFAULT 5 CHECK (rating >= 1 AND rating <= 5),
  message TEXT NOT NULL,
  is_displayed BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "testimonials_public_read" ON testimonials;
CREATE POLICY "testimonials_public_read" ON testimonials FOR SELECT USING (true);

DROP POLICY IF EXISTS "testimonials_public_insert" ON testimonials;
CREATE POLICY "testimonials_public_insert" ON testimonials FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "admin_all_testimonials" ON testimonials;
CREATE POLICY "admin_all_testimonials" ON testimonials FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');
