-- ==========================================
-- Album Portfolio - 1 card 1 album pasangan
-- ==========================================
CREATE TABLE IF NOT EXISTS public.website_albums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL DEFAULT 'Album',
    couple_name TEXT NOT NULL DEFAULT '',
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    cover_image_path TEXT NOT NULL DEFAULT '',
    is_active BOOLEAN DEFAULT TRUE,
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.website_album_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id BIGINT REFERENCES public.website_albums(id) ON DELETE CASCADE NOT NULL,
    image_path TEXT NOT NULL,
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_website_albums_active ON public.website_albums(is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_website_albums_category ON public.website_albums(category_id);
CREATE INDEX IF NOT EXISTS idx_website_album_photos_album ON public.website_album_photos(album_id, sort_order);

ALTER TABLE public.website_albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_album_photos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "website_albums_public_select" ON public.website_albums;
CREATE POLICY "website_albums_public_select" ON public.website_albums FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "website_albums_admin_all" ON public.website_albums;
CREATE POLICY "website_albums_admin_all" ON public.website_albums FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "website_album_photos_public_select" ON public.website_album_photos;
CREATE POLICY "website_album_photos_public_select" ON public.website_album_photos FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "website_album_photos_admin_all" ON public.website_album_photos;
CREATE POLICY "website_album_photos_admin_all" ON public.website_album_photos FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP TRIGGER IF EXISTS trg_website_albums_updated ON public.website_albums;
CREATE TRIGGER trg_website_albums_updated
    BEFORE UPDATE ON public.website_albums
    FOR EACH ROW EXECUTE FUNCTION update_website_timestamp();
