-- ==========================================
-- 1. CLEANUP / RESET DATABASE SCHEMA
-- ==========================================
DROP TABLE IF EXISTS project_progress CASCADE;
DROP TABLE IF EXISTS booking_addons CASCADE;
DROP TABLE IF EXISTS booking_details CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS addons CASCADE;
DROP TABLE IF EXISTS packages CASCADE;
DROP TABLE IF EXISTS sub_categories CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

DROP TYPE IF EXISTS dp_type_enum CASCADE;
DROP TYPE IF EXISTS booking_status_type CASCADE;
DROP TYPE IF EXISTS location_type_enum CASCADE;
DROP TYPE IF EXISTS retouch_status_type CASCADE;
DROP TYPE IF EXISTS printing_status_type CASCADE;
DROP TYPE IF EXISTS workflow_status_type CASCADE;

-- ==========================================
-- 2. ENUM TYPES CREATION
-- ==========================================
CREATE TYPE dp_type_enum AS ENUM ('PERCENTAGE', 'FIXED');
CREATE TYPE booking_status_type AS ENUM ('CONSULTATION', 'BOOKED', 'COMPLETED', 'CANCELLED');
CREATE TYPE location_type_enum AS ENUM ('KOTA_TASIK', 'LUAR_KOTA');
CREATE TYPE retouch_status_type AS ENUM ('PENDING', 'IN_PROGRESS', 'DONE');
CREATE TYPE printing_status_type AS ENUM ('NOT_STARTED', 'IN_PRINTING', 'READY_FOR_PICKUP', 'DELIVERED');
CREATE TYPE workflow_status_type AS ENUM ('SHOOTING', 'EDIT', 'PRINTING', 'READY', 'DELIVERED');

-- ==========================================
-- 3. TABLES SCHEMA DEFINITION
-- ==========================================

-- 3.1 Categories (Kategori Utama)
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    icon VARCHAR(64) DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3.2 Sub Categories (Sub-Kategori Layanan)
CREATE TABLE sub_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3.3 Packages (Daftar Paket Layanan + Dynamic DP Config)
CREATE TABLE packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sub_category_id BIGINT REFERENCES sub_categories(id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    duration_hours INT,
    crew_info TEXT,
    inclusions TEXT NOT NULL,
    dp_value DECIMAL(12, 2) DEFAULT 200000.00,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3.4 Addons (Layanan Tambahan)
CREATE TABLE addons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    price DECIMAL(12, 2) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3.5 Clients (Data Pelanggan)
CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR NOT NULL,
    whatsapp_number VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3.6 Bookings (Transaksi Booking)
CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number VARCHAR UNIQUE NOT NULL,
    client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
    event_date DATE NOT NULL,
    booking_date DATE DEFAULT CURRENT_DATE,
    location_type location_type_enum DEFAULT 'KOTA_TASIK',
    event_address TEXT NOT NULL,
    subtotal DECIMAL(12, 2) NOT NULL,
    transport_fee DECIMAL(12, 2) DEFAULT 0,
    grand_total DECIMAL(12, 2) NOT NULL,
    dp_amount DECIMAL(12, 2) NOT NULL,
    status booking_status_type DEFAULT 'CONSULTATION',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    dp_paid_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    paid_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    source VARCHAR(20) DEFAULT 'CLIENT',
    vendor_name TEXT
);

-- 3.7 Booking Details (Detail Paket yang Dipilih)
CREATE TABLE booking_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
    package_id BIGINT REFERENCES packages(id) ON DELETE RESTRICT,
    price_at_booking DECIMAL(12, 2) NOT NULL
);

-- 3.8 Booking Addons (Detail Add-ons yang Dipilih)
CREATE TABLE booking_addons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
    addon_id BIGINT REFERENCES addons(id) ON DELETE RESTRICT,
    price_at_booking DECIMAL(12, 2) NOT NULL,
    qty INT DEFAULT 1
);

-- 3.9 Project Progress (Tracking SLA Editor & Cetak)
CREATE TABLE project_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE UNIQUE,
    progress_status workflow_status_type DEFAULT 'SHOOTING',
    notes TEXT,
    drive_link TEXT,
    expected_date DATE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ==========================================
-- 4. INDEXES
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_bookings_event_date ON bookings(event_date);
CREATE INDEX IF NOT EXISTS idx_bookings_status ON bookings(status);
CREATE INDEX IF NOT EXISTS idx_bookings_client_id ON bookings(client_id);
CREATE INDEX IF NOT EXISTS idx_packages_sub_category ON packages(sub_category_id);
CREATE INDEX IF NOT EXISTS idx_sub_categories_category ON sub_categories(category_id);

-- ==========================================
-- 5. SEED DATA INSERTION
-- ==========================================

-- 5.1 Insert Categories
INSERT INTO categories (id, name) VALUES 
(1, 'WEDDING'),
(2, 'PRAWEDDING'),
(3, 'ENGAGEMENT'),
(4, 'EVENT'),
(5, 'WEDDING CONTENT CREATOR');

-- 5.2 Insert Sub-Categories
INSERT INTO sub_categories (id, category_id, name) VALUES 
(1, 1, 'FILE ONLY'),
(2, 1, 'PHOTO ONLY'),
(3, 1, 'PHOTO & VIDEO'),
(4, 2, 'OUTDOOR'),
(5, 2, 'STUDIO'),
(6, 2, 'STUDIO PHOTO ONLY'),
(7, 3, 'PRINTED ALBUM'),
(8, 3, 'FILE ONLY'),
(9, 4, 'SPECIAL EVENT'),
(10, 5, 'WCC PACKAGE');

-- 5.3 Insert Packages (dp_value = nominal DP dalam Rupiah)
INSERT INTO packages (sub_category_id, name, price, duration_hours, crew_info, inclusions, dp_value) VALUES 
-- WEDDING - FILE ONLY
(1, 'File Only Team', 800000, 6, '1 Photographer (Team)', 'Soft file full, Photo Retouch, All file backup Flashdisk', 250000),
(1, 'File Only Owner', 1200000, 8, '1 Photographer (Owner)', 'Soft file full, Photo Retouch, All file backup Flashdisk', 350000),

-- WEDDING - PHOTO ONLY
(2, 'Royal', 4300000, 8, '2 Photographer (Owner & Team), 1 Assistant, 1 WCC', 'Soft file full album, Photo Retouch, 2 Album Magazine, Box Album Exclusive, WCC, 2 Pembesaran 16RP, All file backup Flashdisk', 1350000),
(2, 'Premium', 2900000, 8, '1 Photographer (Owner), 1 Assistant, 1 WCC', 'Soft file full album, Photo Retouch, Album Magazine, Album Magnetik, Box Album Exclusive, 1 Pembesaran 16RP, All file backup Flashdisk', 900000),
(2, 'Silver', 1900000, 8, '1 Photographer (Team/Owner), 1 Assistant', 'Soft file full album, Photo Retouch, Album Magazine, All file backup Flashdisk', 600000),
(2, 'Medium', 1400000, 8, '1 Photographer (Team)', 'Soft file full album, Photo Retouch, Album Magnetik, All file backup Flashdisk', 450000),

-- WEDDING - PHOTO & VIDEO
(3, 'Royal', 5300000, 9, '2 Photographer (Owner & Team), 1 Videographer, 1 Assistant, 1 WCC', 'Soft file full album, Video Cinematic 3-4 Menit, Full Photo Retouch, 1 Album Magazine, 1 Album Magazine (Poker), Box Album Exclusive, 2 Pembesaran 16RP, Free Background, WCC, All file backup Flashdisk', 1650000),
(3, 'Premium', 4000000, 8, '1 Photographer (Owner), 1 Videographer, 1 Assistant', 'Soft file full album, Video Cinematic 2-3 Menit, Full Photo Retouch, Album Magazine, Album Magnetik (Poker), Box Album Exclusive Wood, 1 Pembesaran 16RP, Free Background, Free BTS, All file backup Flashdisk', 1250000),
(3, 'Silver', 3000000, 7, '1 Photographer (Team/Owner), 1 Videographer', 'Soft file full album, Video Cinematic 2-3 Menit, Photo Retouch, Album Magazine, All file backup Flashdisk', 950000),
(3, 'Medium', 2500000, 7, '1 Photographer (Team), 1 Videographer', 'Soft file full album, Video Cinematic 1-2 Menit, Photo Retouch, Album Magnetik, All file backup Flashdisk', 800000),

-- PRAWEDDING - OUTDOOR
(4, 'Royal', 3400000, NULL, NULL, '2 Konsep, 2 Wardrobe, Makeup & Touch Up, 2 Pembesaran 16RP Motion, 2 Pembesaran 12RP, 2 Pembesaran 8R, 6 Pembesaran 4R, Photo retouch, All file backup Flashdisk', 1050000),
(4, 'Premium', 2800000, NULL, NULL, '2 Konsep, Makeup & Touch Up, 2 Pembesaran 16RP, 2 Pembesaran 8RP, 4 Pembesaran 4R, Photo retouch, All file backup Flashdisk', 850000),
(4, 'Medium', 1500000, NULL, NULL, '2 Konsep, 1 Pembesaran 16RP, 2 Pembesaran 8RP, 3 Pembesaran 4R, Photo retouch, All file backup Flashdisk', 450000),

-- PRAWEDDING - STUDIO
(5, 'Premium', 2700000, 3, NULL, '2 Konsep, 2 Wardrobe, Makeup & Touch Up, 2 Pembesaran 16RP Frame Motion, 2 Pembesaran 8RP, 5 Pembesaran 4R, BTS, Photo Retouch, All file backup GDrive', 850000),
(5, 'Standard', 2000000, 2, NULL, '2 Konsep, Makeup & Touch Up, 1 Wardrobe, 2 Pembesaran 12RP, 2 Pembesaran 8RP, Photo Retouch, All file backup GDrive', 600000),
(5, 'Basic', 1500000, 1, NULL, '1 Konsep, Makeup & Wardrobe, 1 Pembesaran 12RP, 2 Cetak 4R, Photo Retouch, All file backup GDrive', 450000),

-- PRAWEDDING - STUDIO PHOTO ONLY
(6, 'Premium', 1600000, 2, NULL, '2 Konsep, 2 Pembesaran 16RP, 2 Pembesaran 8RP, 4 Pembesaran 4R, Photo Retouch, All file backup GDrive', 500000),
(6, 'Standard', 1200000, 2, NULL, '2 Konsep, 2 Pembesaran 12RP, 2 Pembesaran 8RP, Photo Retouch, All file backup GDrive', 350000),
(6, 'Basic', 800000, 1, NULL, '1 Konsep, 1 Pembesaran 12RP, 2 Cetak 4R, Photo Retouch, All file backup GDrive', 250000),

-- ENGAGEMENT - PRINTED ALBUM
(7, '1M Package', 1000000, NULL, NULL, '1 Album Magnetic, 40 Cetak File, Full Retouch, Backup Flashdisk', 300000),
(7, '1.7M Package', 1700000, NULL, NULL, '1 Album Magazine, Full Retouch, Backup Flashdisk', 550000),
(7, '2.5M Package', 2500000, NULL, NULL, '1 Album Magazine, Video Teaser 1 Menit, Full Retouch, Backup Flashdisk', 800000),

-- ENGAGEMENT - FILE ONLY
(8, 'File Only', 650000, 4, NULL, 'Soft file full, Photo Retouch, All file backup GDrive/Flashdisk', 200000),

-- EVENT
(9, 'Graduation', 300000, 1, '1 Photographer (Team)', 'Soft file full, Photo Retouch, All file backup GDrive', 100000),
(9, 'Birthday', 500000, 2, '1 Photographer (Team)', 'Soft file full, Photo Retouch, All file backup GDrive', 150000),
(9, 'Khitan', 650000, 4, '1 Photographer (Team)', 'Soft file full, Photo Retouch, All file backup GDrive', 200000),
(9, 'Maternity', 250000, 1, '1 Photographer (Team)', 'Soft file full, Photo Retouch, All file backup GDrive', 100000),

-- WEDDING CONTENT CREATOR (WCC)
(10, 'Bronze (Akad Only)', 300000, 5, NULL, 'Up to 7 IG Story, 1 Video Content, 1 IG Reel, Unlimited Shots', 100000),
(10, 'Platinum (Resepsi)', 400000, 7, NULL, 'Up to 10 IG Story, 2 Video Content, 1 IG Reel, Unlimited Shots', 100000),
(10, 'Diamond (Full Acara)', 500000, 8, NULL, 'Up to 15 IG Story, 3 Video Content, 1 IG Reel, Unlimited Shots', 150000);

SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT MAX(id) FROM categories), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('sub_categories', 'id'), COALESCE((SELECT MAX(id) FROM sub_categories), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('packages', 'id'), COALESCE((SELECT MAX(id) FROM packages), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('addons', 'id'), COALESCE((SELECT MAX(id) FROM addons), 0) + 1, false);

-- 5.4 Insert Add-Ons List
INSERT INTO addons (name, price) VALUES
('Traditional Ceremony (Siraman) Photo Only', 500000),
('Traditional Ceremony (Siraman) Photo & Video', 800000),
('Penambahan Background Outdoor 3x4', 250000),
('Penambahan Mini Studio 6x6', 600000),
('Penambahan Clip Video 1 Menit', 400000),
('Video Teaser 1 Menit', 700000),
('Video Cinematic 2 Menit', 1200000),
('Video Cinematic 3 Menit', 1500000),
('Video Cinematic 3 Menit (Drone)', 2500000),
('Makeup', 500000),
('1 Wardrobe', 300000),
('2 Wardrobe', 500000),
('Cetak Pembesaran 16RP', 250000),
('Cetak Pembesaran 12RP', 150000),
('Cetak Pembesaran 8RP', 100000);

-- ==========================================
-- 6. ROW LEVEL SECURITY (RLS)
-- ==========================================
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE sub_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_progress ENABLE ROW LEVEL SECURITY;

-- Anonymous reads (katalog + pengecekan status)
CREATE POLICY "categories_public_read" ON categories FOR SELECT USING (true);
CREATE POLICY "sub_categories_public_read" ON sub_categories FOR SELECT USING (true);
CREATE POLICY "packages_public_read" ON packages FOR SELECT USING (true);
CREATE POLICY "addons_public_read" ON addons FOR SELECT USING (true);
CREATE POLICY "bookings_public_read" ON bookings FOR SELECT USING (true);
CREATE POLICY "clients_public_read" ON clients FOR SELECT USING (true);
CREATE POLICY "booking_details_public_read" ON booking_details FOR SELECT USING (true);
CREATE POLICY "booking_addons_public_read" ON booking_addons FOR SELECT USING (true);
CREATE POLICY "project_progress_public_read" ON project_progress FOR SELECT USING (true);

-- Anonymous inserts (alur booking)
CREATE POLICY "clients_public_insert" ON clients FOR INSERT WITH CHECK (true);
CREATE POLICY "bookings_public_insert" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "booking_details_public_insert" ON booking_details FOR INSERT WITH CHECK (true);
CREATE POLICY "booking_addons_public_insert" ON booking_addons FOR INSERT WITH CHECK (true);

-- Admin (authenticated) full akses ke seluruh tabel manajemen
CREATE POLICY "admin_all_categories" ON categories FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "admin_all_sub_categories" ON sub_categories FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "admin_all_packages" ON packages FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "admin_all_addons" ON addons FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "admin_all_clients" ON clients FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "admin_all_bookings" ON bookings FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "admin_all_booking_details" ON booking_details FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "admin_all_booking_addons" ON booking_addons FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "admin_all_project_progress" ON project_progress FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- ==========================================
-- 7. TRIGGER: update project_progress.updated_at
-- ==========================================
CREATE OR REPLACE FUNCTION update_progress_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_project_progress_updated ON project_progress;
CREATE TRIGGER trg_project_progress_updated
  BEFORE UPDATE ON project_progress
  FOR EACH ROW EXECUTE FUNCTION update_progress_timestamp();

-- ==========================================
-- MIGRATION: add icon column if missing (safe to run multiple times)
-- ==========================================
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'categories' AND column_name = 'icon'
  ) THEN
    ALTER TABLE categories ADD COLUMN icon VARCHAR(64) DEFAULT NULL;
  END IF;
END $$;

UPDATE categories SET icon = 'Gem'        WHERE name = 'WEDDING' AND icon IS NULL;
UPDATE categories SET icon = 'Camera'     WHERE name = 'PRAWEDDING' AND icon IS NULL;
UPDATE categories SET icon = 'Heart'      WHERE name = 'ENGAGEMENT' AND icon IS NULL;
UPDATE categories SET icon = 'PartyPopper'WHERE name = 'EVENT' AND icon IS NULL;
UPDATE categories SET icon = 'Clapperboard' WHERE name = 'WEDDING CONTENT CREATOR' AND icon IS NULL;
UPDATE categories SET icon = 'GraduationCap' WHERE name = 'GRADUATION' AND icon IS NULL;
