-- ==========================================
-- Testimonials — schema + RLS + migrasi kolom balasan admin
-- Jalankan 1x. Idempotent (aman di-run ulang).
-- ==========================================

CREATE TABLE IF NOT EXISTS public.testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE UNIQUE,
  client_name TEXT NOT NULL,
  rating SMALLINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  message TEXT NOT NULL,
  admin_reply TEXT,
  admin_replied_at TIMESTAMPTZ,
  is_displayed BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now())
);

ALTER TABLE public.testimonials ADD COLUMN IF NOT EXISTS admin_reply TEXT;
ALTER TABLE public.testimonials ADD COLUMN IF NOT EXISTS admin_replied_at TIMESTAMPTZ;
ALTER TABLE public.testimonials ADD COLUMN IF NOT EXISTS is_displayed BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE public.testimonials ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc', now());

CREATE INDEX IF NOT EXISTS idx_testimonials_booking_id ON public.testimonials(booking_id);
CREATE INDEX IF NOT EXISTS idx_testimonials_is_displayed_created ON public.testimonials(is_displayed, created_at DESC);

ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "testimonials_public_select" ON public.testimonials;
CREATE POLICY "testimonials_public_select" ON public.testimonials FOR SELECT USING (is_displayed = true);

DROP POLICY IF EXISTS "testimonials_authenticated_all" ON public.testimonials;
CREATE POLICY "testimonials_authenticated_all" ON public.testimonials FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "testimonials_service_all" ON public.testimonials;
CREATE POLICY "testimonials_service_all" ON public.testimonials FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.update_testimonials_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_testimonials_updated ON public.testimonials;
CREATE TRIGGER trg_testimonials_updated
  BEFORE UPDATE ON public.testimonials
  FOR EACH ROW EXECUTE FUNCTION public.update_testimonials_timestamp();
