-- ==========================================
-- Konten Dinamis Halaman /website
-- Jalankan di Supabase SQL Editor
-- ==========================================

-- ==========================================
-- 1. Tabel Konten Website (singleton, pola = linktree_settings)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.website_settings (
    id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),

    -- Branding & Hero
    site_name TEXT DEFAULT 'Mstory.id',
    logo_url TEXT,                            -- full public URL hasil getPublicUrl()
    hero_slides TEXT[] DEFAULT '{}',          -- full public URL tiap slide (folder website/hero/)
    hero_duration_ms INT DEFAULT 3800,        -- durasi auto-slide (ms)

    -- Intro / About (#about)
    intro_heading TEXT DEFAULT 'Halo, kami Mstory.id',
    intro_text TEXT DEFAULT 'Kami percaya setiap momen layak dikenang bukan hanya apa adanya, tetapi bagaimana momen itu terasa. Lewat bidikan kamera, kami menghadirkan yang paling berharga — merawat tradisi dan bercerita tanpa kata. Di sini, kenangan diabadikan untuk selamanya.',

    -- Info Banner
    info_heading TEXT DEFAULT 'Sampai jumpa di momen Anda',
    info_text TEXT DEFAULT 'Terima kasih telah meluangkan waktu menelusuri karya kami. Semoga langkah kita bisa bertemu, dan kami diberi kesempatan mengabadikan kisah Anda selanjutnya.',
    info_image TEXT,                          -- full public URL (folder website/info/, opsional)
    info_button_label TEXT DEFAULT 'Hubungi kami',

    -- Instagram Section
    instagram_handle TEXT DEFAULT 'mstory.id',
    instagram_url TEXT DEFAULT 'https://instagram.com/mstory.id',
    instagram_grid_count INT DEFAULT 4,       -- jumlah foto grid (2x2)

    -- Contact / CTA
    contact_heading TEXT DEFAULT 'Siap mengabadikan cerita Anda?',
    contact_text TEXT DEFAULT 'Konsultasi gratis — pilih paket, cek tanggal tersedia, lalu lanjut ke booking.',
    wa_number TEXT DEFAULT '6281234567890',
    wa_button_label TEXT DEFAULT 'WhatsApp Admin',
    booking_label TEXT DEFAULT 'Booking Online',
    booking_url TEXT DEFAULT '/?booking=true',

    -- Footer
    footer_copyright TEXT DEFAULT 'Hak cipta dilindungi',

    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

INSERT INTO public.website_settings (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.website_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "website_settings_public_select" ON public.website_settings;
CREATE POLICY "website_settings_public_select"
    ON public.website_settings
    FOR SELECT
    TO public
    USING (true);

DROP POLICY IF EXISTS "website_settings_admin_all" ON public.website_settings;
CREATE POLICY "website_settings_admin_all"
    ON public.website_settings
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- ==========================================
-- 2. Galeri / Grid Portfolio Halaman Website
--    (dikelola admin: urutan, aktif, link)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.website_gallery_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT DEFAULT 'portfolio',
    image_path TEXT NOT NULL,                 -- full public URL (folder website/gallery/)
    link_url TEXT,                            -- opsional: href tujuan
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    sort_order INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Kolom kategori untuk galeri (idempotent saat tabel sudah ada)
ALTER TABLE public.website_gallery_items
    ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_website_gallery_active ON public.website_gallery_items(is_active, sort_order);

ALTER TABLE public.website_gallery_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "website_gallery_public_select" ON public.website_gallery_items;
CREATE POLICY "website_gallery_public_select"
    ON public.website_gallery_items
    FOR SELECT
    TO public
    USING (true);

DROP POLICY IF EXISTS "website_gallery_admin_all" ON public.website_gallery_items;
CREATE POLICY "website_gallery_admin_all"
    ON public.website_gallery_items
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- ==========================================
-- 3. Trigger: update updated_at otomatis
-- ==========================================
CREATE OR REPLACE FUNCTION update_website_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_website_settings_updated ON public.website_settings;
CREATE TRIGGER trg_website_settings_updated
    BEFORE UPDATE ON public.website_settings
    FOR EACH ROW EXECUTE FUNCTION update_website_timestamp();

DROP TRIGGER IF EXISTS trg_website_gallery_updated ON public.website_gallery_items;
CREATE TRIGGER trg_website_gallery_updated
    BEFORE UPDATE ON public.website_gallery_items
    FOR EACH ROW EXECUTE FUNCTION update_website_timestamp();

-- ==========================================
-- 4. Penyimpanan Foto
--    Bucket 'website' (pisah dari fanspage: fanspage=banner/logo, website=hero/info/gallery/albums)
--    publik baca + admin CRUD via policy bucket-level.
--    Puzzle folder di dalam bucket:
--      website/hero/             -> slide hero
--      website/info/             -> background info banner (opsional)
--      website/gallery/          -> foto grid portfolio & instagram (legacy)
--      website/albums/covers/    -> cover album (1 per event)
--      website/albums/photos/    -> foto isi album (zoom click)
--
--    Jika bucket belum ada, jalankan blok berikut:
-- ==========================================
-- INSERT INTO storage.buckets (id, name, public)
-- VALUES ('website', 'website', true)
-- ON CONFLICT (id) DO NOTHING;
--
-- DROP POLICY IF EXISTS "fanspage_public_read" ON storage.objects;
-- CREATE POLICY "fanspage_public_read"
--     ON storage.objects FOR SELECT TO public
--     USING (bucket_id = 'fanspage');
--
-- DROP POLICY IF EXISTS "fanspage_authenticated_insert" ON storage.objects;
-- CREATE POLICY "fanspage_authenticated_insert"
--     ON storage.objects FOR INSERT TO authenticated
--     WITH CHECK (bucket_id = 'fanspage');
--
-- DROP POLICY IF EXISTS "fanspage_authenticated_update" ON storage.objects;
-- CREATE POLICY "fanspage_authenticated_update"
--     ON storage.objects FOR UPDATE TO authenticated
--     USING (bucket_id = 'fanspage') WITH CHECK (bucket_id = 'fanspage');
--
-- DROP POLICY IF EXISTS "fanspage_authenticated_delete" ON storage.objects;
-- CREATE POLICY "fanspage_authenticated_delete"
--     ON storage.objects FOR DELETE TO authenticated
--     USING (bucket_id = 'fanspage');